// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { StringValue } from 'ms';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',

  // migrate: {
  //   path: 'prisma/migrations',
  // },

  datasource: {
    url: process.env.DATABASE_URL as StringValue,
  },
});
