export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',

  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  USER_NOT_FOUND = 'USER_NOT_FOUND',

  TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',

  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
